spring:
  application:
    name: zuul-server
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8101/eureka/
      instance:
        prefer-ip-address: true
      management:
        security:
          enabled: false
server:
  port: 8103
ribbon:
  ReadTimeout: 5000

  ConnectTimeout: 1000


zuul:
  retryable: false
  # host-header
  add-host-header: true

  routes:
    service-a:
      path: /service/**
      serviceId: service-a